org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = tweakerge
mod_name = Tweakerge
author = masa
mod_file_name = tweakerge

# Current mod version
mod_version = 0.5.0

# Required malilib version
malilib_version = 0.5.2+mc26.1.2

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

neoforge_version = 26.1.2.66-beta

conditionalmixin_version = 0.6.4
