[versions]
range-fml = "[4,)"
range-game = "[26,)"
range-neoforge = "[26,)"
range-mafglib = "[0.4,)"

mod-link = "https://github.com/CagayakeGirls/tweakeroo-neoforge"

version-env = "client"
version-type = "beta"

platformId-curseforge = "915857"
platformId-modrinth = "yke6wdGF"

architectury-loom = "1.14-SNAPSHOT"
modpublisher = "2.+"

[plugins]
architectury-loom = { id = "dev.architectury.loom-no-remap", version.ref = "architectury-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }